version: '3.8'

services:
  postgres_prd:
    image: postgres:16-alpine
    container_name: postgres_prd
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres_prod_pass
      POSTGRES_DB: app_prd
    ports:
      - "5432:5432"
    volumes:
      - pgdata_prd:/var/lib/postgresql/data

  api_prd:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    container_name: api_prd
    restart: always
    ports:
      - "3000:3000"
    env_file:
      - .env.production
    volumes:
      - uploads_prd:/usr/src/app/uploads
    depends_on:
      - postgres_prd

volumes:
  pgdata_prd:
  uploads_prd: